# Generated by Django 6.0.6 on 2026-06-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('church_admin', 'Church Administrator'), ('pastor', 'Pastor'), ('finance_officer', 'Finance Officer'), ('secretary', 'Secretary')], default='secretary', help_text="User's role determines their access level", max_length=50),
        ),
    ]
