# Generated by Django 6.0.4 on 2026-06-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_church_admin',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('church_admin', 'Church Administrator'), ('pastor', 'Pastor'), ('finance_officer', 'Finance Officer'), ('secretary', 'Secretary')], default='secretary', help_text="User's role determines their access level", max_length=50),
        ),
    ]
