# Generated by Django 6.0.4 on 2026-04-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('tithe', 'Tithe'), ('offering', 'Offering'), ('donation', 'Donation'), ('special', 'Special Seed'), ('other', 'Other')], default='offering', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile Money'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque')], default='cash', max_length=20)),
                ('reference', models.CharField(blank=True, help_text='Transaction reference or receipt number', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(blank=True, help_text='Leave blank for anonymous contributions', null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.member')),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'ordering': ['-date', '-recorded_at'],
            },
        ),
    ]
