# Generated by Django 6.0.4 on 2026-06-02 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='organizations.church')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finance.account')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Chart of Accounts',
                'ordering': ['code'],
                'unique_together': {('church', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('expense_created', 'Expense Created'), ('expense_updated', 'Expense Updated'), ('expense_approved', 'Expense Approved'), ('expense_rejected', 'Expense Rejected'), ('expense_deleted', 'Expense Deleted'), ('fund_credited', 'Fund Credited'), ('fund_debited', 'Fund Debited'), ('service_posted', 'Service Income Posted'), ('service_reversed', 'Service Income Reversed'), ('entry_voided', 'Journal Entry Voided')], max_length=50)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.church')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='zinc', help_text='Tailwind color name for UI badges', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, help_text='Expense account this category posts to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_categories', to='finance.account')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='organizations.church')),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
                'ordering': ['name'],
                'unique_together': {('church', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(help_text='Short reference code e.g. BLD001, WLF001', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, help_text='Starting balance when this fund was created', max_digits=12)),
                ('funding_source', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('momo', 'Mobile Money'), ('donation', 'Donation'), ('other', 'Other')], default='cash', help_text='Where the initial deposit came from', max_length=20)),
                ('is_restricted', models.BooleanField(default=False, help_text="Money can only be used for this fund's designated purpose")),
                ('approval_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='Expenses above this amount require senior approval (leave blank to disable)', max_digits=12, null=True)),
                ('assigned_ministry', models.CharField(blank=True, help_text='e.g. Youth Ministry, Media Team, Welfare Team', max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='organizations.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fund',
                'verbose_name_plural': 'Funds',
                'ordering': ['name'],
                'unique_together': {('church', 'code'), ('church', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExpenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('momo', 'Mobile Money'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=20)),
                ('receipt_url', models.FileField(blank=True, null=True, upload_to='finance/receipts/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.expensecategory')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='organizations.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_created', to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.fund')),
            ],
            options={
                'verbose_name': 'Expense Record',
                'verbose_name_plural': 'Expense Records',
                'ordering': ['-expense_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit (Income)'), ('debit', 'Debit (Expense)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=255)),
                ('reference_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_transactions', to='organizations.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.fund')),
            ],
            options={
                'ordering': ['-reference_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('transaction_date', models.DateField()),
                ('posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='organizations.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('expense_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entry', to='finance.expenserecord')),
            ],
            options={
                'verbose_name': 'Journal Entry',
                'verbose_name_plural': 'Journal Entries',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('memo', models.CharField(blank=True, max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='finance.account')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
            ],
            options={
                'verbose_name': 'Journal Line',
            },
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('first_offering', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='1st Offering')),
                ('second_offering', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='2nd Offering')),
                ('jy_offering', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='JY Offering')),
                ('children_offering', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Children's Service Offering")),
                ('tithe', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tithe')),
                ('thanksgiving', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Thanksgiving')),
                ('other_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Other Amount')),
                ('other_description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Description')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offerings', to='organizations.church')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_offerings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Offering Record',
                'verbose_name_plural': 'Service Offering Records',
                'ordering': ['-date', '-recorded_at'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='service_offering',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entry', to='finance.serviceoffering'),
        ),
        migrations.AddField(
            model_name='expenserecord',
            name='related_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='finance.serviceoffering'),
        ),
    ]
