# Generated by Django 6.0.4 on 2026-04-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Name of the service or event (e.g. "Sunday Service – 4th May 2025")', max_length=300)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, help_text="Extra notes about this service's finances", null=True)),
                ('first_offering', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='1st Offering')),
                ('second_offering', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='2nd Offering')),
                ('jy_offering', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='JY Offering')),
                ('children_offering', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Children's Service Offering")),
                ('tithe', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tithe')),
                ('thanksgiving', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Thanksgiving')),
                ('other_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Other Amount')),
                ('other_description', models.CharField(blank=True, help_text='Specify what "Other" is (e.g. Building Fund, Welfare)', max_length=200, null=True, verbose_name='Other Description')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Offering Record',
                'verbose_name_plural': 'Service Offering Records',
                'ordering': ['-date', '-recorded_at'],
            },
        ),
        migrations.DeleteModel(
            name='Contribution',
        ),
    ]
