# Generated by Django 6.0.4 on 2026-05-21 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_fund_alter_serviceoffering_event_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fund',
            name='is_active',
        ),
        migrations.AddField(
            model_name='fund',
            name='approval_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expenses above this amount require senior approval (leave blank to disable)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='assigned_ministry',
            field=models.CharField(blank=True, help_text='e.g. Youth Ministry, Media Team, Welfare Team', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fund',
            name='code',
            field=models.CharField(default='FUND001', help_text='Short reference code e.g. BLD001, WLF001', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fund',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funds_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fund',
            name='funding_source',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('momo', 'Mobile Money'), ('donation', 'Donation'), ('other', 'Other')], default='cash', help_text='Where the initial deposit came from', max_length=20),
        ),
        migrations.AddField(
            model_name='fund',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Starting balance when this fund was created', max_digits=12),
        ),
        migrations.AddField(
            model_name='fund',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='fund',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fund',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text="Money can only be used for this fund's designated purpose"),
        ),
    ]
