# Generated by Django 6.0.4 on 2026-05-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_remove_fund_is_active_fund_approval_threshold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund',
            name='code',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated unique fund code', max_length=20, unique=True),
        ),
    ]
