# Generated by Django 6.0.4 on 2026-06-02 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Type the name of the service or event (e.g. "Sunday 29th April 2025")', max_length=300)),
                ('service_type', models.CharField(choices=[('sunday', 'Sunday Service'), ('midweek', 'Midweek Service'), ('special', 'Special Service'), ('prayer', 'Prayer Meeting'), ('youth', 'Youth Service'), ('other', 'Other')], default='sunday', max_length=20)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('adults_male', models.PositiveIntegerField(default=0, verbose_name='Adults Male')),
                ('adults_female', models.PositiveIntegerField(default=0, verbose_name='Adults Female')),
                ('junior_youth_male', models.PositiveIntegerField(default=0, verbose_name='Junior Youth Male')),
                ('junior_youth_female', models.PositiveIntegerField(default=0, verbose_name='Junior Youth Female')),
                ('children_male', models.PositiveIntegerField(default=0, verbose_name='Children Male')),
                ('children_female', models.PositiveIntegerField(default=0, verbose_name='Children Female')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_attendances', to='organizations.church')),
            ],
            options={
                'verbose_name': 'Service Attendance',
                'verbose_name_plural': 'Service Attendances',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
