# Generated by Django 6.0.4 on 2026-04-29 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('sunday', 'Sunday Service'), ('midweek', 'Midweek Service'), ('special', 'Special Service'), ('prayer', 'Prayer Meeting'), ('youth', 'Youth Service')], default='sunday', max_length=20)),
                ('date', models.DateField()),
                ('title', models.CharField(blank=True, help_text='Optional title (e.g., "Easter Sunday")', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.service')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-service__date'],
                'unique_together': {('member', 'service')},
            },
        ),
    ]
